Add files via upload
vikadmin88/CurrencyChatBot pull request #7
Opened 2023-12-21 16:49 UTC by MNN1107

2023-12-21 22:04 UTC, vikadmin88 requested changes

2023-12-21 22:04 UTC, vikadmin88 commented on src/main/java/org/javacrafters/core/storage/SQLiteStorageProvider.java
> +        String createTableQuery = "CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY, name TEXT)";
name TEXT > json TEXT

2023-12-21 22:04 UTC, vikadmin88 commented on src/main/java/org/javacrafters/core/storage/SQLiteStorageProvider.java
> +        String saveUserQuery = "INSERT INTO users (id, name) VALUES (?, ?)";
Сначала делать селект по userId. Можно использовать public User load (Long userId)
Если юзер есть в базе то делать UPDATE если нет  INSERT

2023-12-21 22:04 UTC, vikadmin88 commented on src/main/java/org/javacrafters/core/storage/SQLiteStorageProvider.java
> +    public void load() {
Здесь реализовать выборку всех(SELECT * FROM users) и в цикле создавать юзеров, добавляя их в коллекцию приложения. (используя Gson())

2023-12-21 22:04 UTC, vikadmin88 commented on src/main/java/org/javacrafters/core/storage/SQLiteStorageProvider.java
> +               return new User(resultSet.getLong("id"), resultSet.getString("name"));
(используя Gson()) из  json  в User object

2023-12-23 21:59 UTC, MNN1107 commented
в build.gradle додала бібліотеку SQLite-JDBC, яка є драйвером JDBC для SQLite: // https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
    implementation group: 'org.xerial', name: 'sqlite-jdbc', version: '3.44.1.0'

2023-12-23 23:07 UTC, vikadmin88 approved these changes
good!

2023-12-23 23:08 UTC, merged